name: Check code qality

on: [push]

jobs:
  code-qality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: install dependencies
        run: pip install black ruff isort
      - name: run formatets
        run: python -m black --check . && python -m isort --check .
      - name: run linter
        run: python -m ruff .